name: Build and Deploy
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print good bye
        run: echo "good bye"
      - name: Multi line exec
        run: |
            echo "First Echo"
            echo "Second Output"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy task
        run: echo "Deployed success"
